import { chromium } from 'playwright';
const exe = process.env.HOME + '/Library/Caches/ms-playwright/chromium-1234/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing';
const b = await chromium.launch({ executablePath: exe });
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
const errs = []; p.on('pageerror', e => errs.push(e.message)); p.on('console', m => m.type() === 'error' && errs.push(m.text()));
await p.goto('http://localhost:4321/produs/cristal-3d-portret', { waitUntil: 'networkidle' });
await p.screenshot({ path: '/tmp/flow0.jpg', type: 'jpeg', quality: 70 });
await p.getByRole('button', { name: 'Personalizează', exact: true }).click();
await p.getByRole('tab', { name: /Fotografia/ }).click();
await p.setInputFiles('input[type=file]', 'public/img/samples/caine.jpg');
await p.waitForTimeout(600);
await p.getByRole('dialog').getByText('Fundalul pozei').waitFor(); await p.waitForFunction(() => !document.querySelector('[role=dialog] .animate-spin'), null, { timeout: 30000 });
await p.screenshot({ path: '/tmp/flowE1.jpg', type: 'jpeg', quality: 70 });
await p.getByRole('tab', { name: /Textul/ }).click();
await p.getByRole('dialog').locator('textarea').fill('Bruno\n2015 – 2026');
await p.getByRole('radio', { name: 'Mașină de scris' }).click();
await p.waitForTimeout(700);
await p.screenshot({ path: '/tmp/flow1.jpg', type: 'jpeg', quality: 70 });
await p.getByRole('dialog').getByRole('button', { name: /Adaugă în coș/ }).click();
await p.waitForTimeout(600);
await p.screenshot({ path: '/tmp/flow2.jpg', type: 'jpeg', quality: 70 });
await p.goto('http://localhost:4321/cos', { waitUntil: 'networkidle' });
await p.fill('input[name=name]', 'Ion Popescu'); await p.fill('input[name=tel]', '0740123456'); await p.fill('input[name=email]', 'ion@example.com');
await p.fill('input[name=street]', 'Str. Lăpușneanu 12'); await p.fill('input[name=city]', 'Iași'); await p.fill('input[name=county]', 'Iași');
await p.screenshot({ path: '/tmp/flow3.jpg', type: 'jpeg', quality: 70 });
await p.check('input[type=checkbox][required]');
await p.getByRole('button', { name: /Plătește/ }).click();
await p.waitForTimeout(500);
console.log('done text:', await p.locator('h1').first().innerText());
console.log('errors', JSON.stringify(errs));
await b.close();
